### ISSUE TITLE
'rockstar developers'

### ISSUE THREAD

**Issue by chneau** [RoanixS2k12/git-presentation#1]
https://github.com/RoanixS2k12/git-presentation/blob/17562c6452acd10588c076bffc0bb62101dbeff0/index.html#L7

See https://github.com/dylanbeattie/rockstar .

**Comment by RoanixS2k12** [comment]
... report ! :)

**Comment by chneau** [comment]
bon ca fait un an que c'est ouvert ! ca commence a faire !
